vich_uploader:
    db_driver: orm
    mappings:
        seed_image:
            uri_prefix: /images/seed
            upload_destination: '%kernel.project_dir%/public/images/seed'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        vegetable_image:
            uri_prefix: /images/vegetable
            upload_destination: '%kernel.project_dir%/public/images/vegetable'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        land_image:
            uri_prefix: /images/land
            upload_destination: '%kernel.project_dir%/public/images/land'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

